# Generated by Django 3.1.6 on 2021-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update timestamp'),
        ),
    ]
