# Generated by Django 3.1.6 on 2021-03-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_weapon_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rifles',
            new_name='Rifle',
        ),
    ]
