# Generated by Django 3.1.6 on 2021-03-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0003_auto_20210328_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weapon',
            new_name='Skin',
        ),
    ]
