# Generated by Django 3.1.6 on 2021-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_auto_20210328_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='subject',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='item description'),
        ),
    ]
